### PR TITLE
Added a logging option for Keycloak server.

### PR DESCRIPTION
**Pull request by masodilosangeles**
I updated the XSL stylesheet to enable logging, controlled by an environment variable called KEYCLOAK_LOGLEVEL.

Default is set to "INFO." I found it useful to be able to set the logging level to DEBUG from the environment while getting my server set up initially.

### CODE REVIEW

**Comment by stianst** [comment]
I like the addition of the logging option, but it should be on the main Keycloak image. If you change that I'm happy to merge it

**Comment by masodilosangeles** [comment]
No problem.

Would you prefer I do that by incorporating a stripped down version of the
XSL file in the main Keycloak image?

Or do you have another mechanism in mind?

**Comment by stianst** [comment]
Stripped down version of xsl file is fine. I'd rather keep it to one mechanism ;)

**Comment by stianst** [comment]
Can you rename server/changeDatabase.xsl to server/setLogLevel.xsl and also drop that part from the server-postgresql/changeDatabase.xsl  and server-mysql/changeDatabase.xsl. They inherit from server so the transformation will already be there.

**Comment by masodilosangeles** [comment]
Will do.

**Comment by masodilosangeles** [comment]
I've incorporated the changes Stian requested so the result is:

1. A new file named `server/setLogLevel.xsl` which allows the Keycloak logging level to be controlled by the environment variable `KEYCLOAK_LOGLEVEL`
2. Updated the `Dockerfile` to execute the new XSL file to update the `standalone.xml` file.
3. Made a minor typo edit to `README.md` in `server/keycloak-postgres` so it doesn't refer to MySQL

**Pull request merged**
